### ISSUE TITLE
Issues with npe2 convert

### ISSUE THREAD

**Issue by jni** [napari/npe2#59]
I ran npe2 convert on affinder at https://github.com/jni/affinder/tree/1b35d64bb8eb57b842ba15162ccbd57048f04280

(Side note: I expected that I would run npe2 convert on my *code*, not on installed plugins. `npe2 convert .` gave me a meaningful error but I kinda would have wanted it to just look at a repo rather than an installed package. Maybe that's harder though.)

1. Running `npe2 convert affinder > napari.yaml` gives a warning, `Invalid schema 'napari:builtins.yaml'`, and no other feedback. It actually succeeded, so a success message should probably also be printed on stderr?
2. npe2 convert puts the napari.yaml in the current directory, but it actually needs to go in the package directory and get added to the manifest, right? That can probably be done automatically?

**Comment by tlambert03** [comment]
> I kinda would have wanted it to just look at a repo rather than an installed package

Yeah, that's kind of the whole point we're moving to npe2 😂 ... because we _had_ to install/import plugins in npe1 to see what they offer. 

> npe2 convert puts the napari.yaml in the current directory

It puts it wherever you tell it to using the `-o` flag, or, here, using the `>`. 
Point taken though.  Currently, all npe2 convert does is generate the manifest, we still need to modify setup.cfg... and that's the point where it really matters where the file ends up.
